USE typhon_cath_crm;

INSERT INTO roles (role_name, description) VALUES
('Super Admin', 'Full system access'),
('Admin', 'Administrative CRM access'),
('Sales User', 'Customer and RFQ pipeline access'),
('Marketing User', 'Campaign management access'),
('Inventory Manager', 'Product and inventory access');

-- Demo password should be replaced with a real password_hash generated by password_hash().
INSERT INTO users (name, email, password_hash, role_id) VALUES
('Demo Admin', 'admin@typhoncath.test', '$2y$10$replace_with_real_hash', 1);

INSERT INTO accounts (account_name, email, phone, industry, source, tags) VALUES
('Demo Hospital', 'contact@demohospital.test', '555-0100', 'Healthcare', 'Seed Data', 'hospital,prospect');

INSERT INTO products (product_name, sku, price, description) VALUES
('Typhon Catheter Demo Product', 'TYPHON-DEMO-001', 499.00, 'Demo product for CRM inventory.');

INSERT INTO inventory (product_id, available_quantity, reserved_quantity) VALUES
(1, 100, 0);
